version: "3"
services:

  coordinator:
    build:
      context: .
      dockerfile: coordinator/coordinator.dockerfile
    image: dev/universalis-coordinator:latest
    ports:
      - "8886:8888"
    environment:
      - KAFKA_URL=kafka1:9092

  worker:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
    image: dev/universalis:latest
    environment:
      - INGRESS_TYPE=KAFKA
      - KAFKA_URL=kafka1:9092
      - DISCOVERY_HOST=coordinator
      - DISCOVERY_PORT=8888

  frontend:
    build:
      context: .
      dockerfile: stateflow-client/frontend.dockerfile
    image: kpsarakis/universalis-demo-frontend:latest
    environment:
      - UNIVERSALIS_HOST=coordinator
      - UNIVERSALIS_PORT=8888
      - PYTHONUNBUFFERED=TRUE
      - KAFKA_URL=kafka1:9092
      - N_PARTITIONS=6
      - N_ENTITIES=5000
      - STARTING_AMOUNT=100
      - SANIC_RESPONSE_TIMEOUT=6000
    depends_on:
      - coordinator
    ports:
      - "5000:5000"
