version: "3"
services:

  frontend:
    build:
      context: .
      dockerfile: demo/frontend.dockerfile
    image: dev/universalis-demo-frontend:latest
    environment:
      - UNIVERSALIS_HOST=coordinator
      - UNIVERSALIS_PORT=8888
      - PYTHONUNBUFFERED=TRUE
    depends_on:
      - coordinator

  frontend-load-balancer:
    image: nginx:latest
    volumes:
      - ./frontend_nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    ports:
      - "5000:80"

#  ingress:
#    build:
#      context: .
#      dockerfile: ingress/ingress.Dockerfile
#    environment:
#      - DISCOVERY_HOST=coordinator
#      - DISCOVERY_PORT=8888
#    image: dev/universalis-ingress:latest
#
#  ingress-load-balancer:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - ingress
#    ports:
#      - "4000:4000"

  coordinator:
    build:
      context: .
      dockerfile: coordinator/coordinator.dockerfile
    image: dev/universalis-coordinator:latest
    ports:
      - "8886:8888"
    environment:
      - KAFKA_URL=kafka1:9092

  worker:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
    image: dev/universalis:latest
    environment:
      - INGRESS_TYPE=KAFKA
      - KAFKA_URL=kafka1:9092
      - DISCOVERY_HOST=coordinator
      - DISCOVERY_PORT=8888


# LOCUST

  locust-master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./locust-loadtest/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://locust-master:8089

  locust-worker:
    image: locustio/locust
    volumes:
      - ./locust-loadtest/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
