version: "3"
services:

  frontend:
    build:
      context: .
      dockerfile: demo/frontend.dockerfile
    image: dev/universalis-demo-frontend:latest
    environment:
      - UNIVERSALIS_HOST=coordinator
      - UNIVERSALIS_PORT=8888
      - PYTHONUNBUFFERED=TRUE
    ports:
      - "5000:5000"
    depends_on:
      - coordinator

  ingress:
    build:
      context: .
      dockerfile: ingress/ingress.Dockerfile
    environment:
      - DISCOVERY_HOST=discovery
      - DISCOVERY_PORT=8888
    image: dev/universalis-ingress:latest

  ingress-load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ingress
    ports:
      - "4000:4000"

  discovery:
    build:
      context: .
      dockerfile: discovery/discovery.Dockerfile
    image: dev/universalis-discovery:latest
    ports:
      - "8885:8888"

  coordinator:
    build:
      context: .
      dockerfile: coordinator/coordinator.dockerfile
    environment:
      - DISCOVERY_HOST=discovery
      - DISCOVERY_PORT=8888
    image: dev/universalis-coordinator:latest
    ports:
      - "8886:8888"

  worker-0:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
    image: dev/universalis:latest
    environment:
      - OWN_ADDRESS_NAME=worker-0
      - OWN_PORT=8887
      - DISCOVERY_HOST=discovery
      - DISCOVERY_PORT=8888
    ports:
      - "8887:8888"

  worker-1:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
    image: dev/universalis:latest
    environment:
      - OWN_ADDRESS_NAME=worker-1
      - OWN_PORT=8888
      - DISCOVERY_HOST=discovery
      - DISCOVERY_PORT=8888
    ports:
      - "8888:8888"

  worker-2:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
    image: dev/universalis:latest
    environment:
      - OWN_ADDRESS_NAME=worker-2
      - OWN_PORT=8889
      - DISCOVERY_HOST=discovery
      - DISCOVERY_PORT=8888
    ports:
      - "8889:8888"

# LOCUST

  locust-master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./locust-loadtest/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://locust-master:8089

  locust-worker:
    image: locustio/locust
    volumes:
      - ./locust-loadtest/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master