version: "3"
services:

  ingress-0:
    build:
      context: .
      dockerfile: ingress/ingress.Dockerfile
    image: dev/universalis-ingress:latest
    ports:
      - "8885:8888"

  coordinator:
    build:
      context: .
      dockerfile: coordinator/coordinator.dockerfile
    image: dev/universalis-coordinator:latest
    ports:
      - "8886:8888"

  worker-0:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
    image: dev/universalis:latest
    environment:
      - PYTHONUNBUFFERED=1
      - OWN_ADDRESS_NAME=worker-0
      - OWN_PORT=8887
    ports:
      - "8887:8888"

  worker-1:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
    image: dev/universalis:latest
    environment:
      - PYTHONUNBUFFERED=1
      - OWN_ADDRESS_NAME=worker-1
      - OWN_PORT=8888
    ports:
      - "8888:8888"

  worker-2:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
    image: dev/universalis:latest
    environment:
      - PYTHONUNBUFFERED=1
      - OWN_ADDRESS_NAME=worker-2
      - OWN_PORT=8889
    ports:
      - "8889:8888"
