version: "3"
services:

  frontend:
    build:
      context: .
      dockerfile: bench/shopping_cart/frontend.dockerfile
    image: dev/universalis-demo-frontend:latest
    environment:
      - UNIVERSALIS_HOST=coordinator
      - UNIVERSALIS_PORT=8888
      - PYTHONUNBUFFERED=TRUE
    depends_on:
      - coordinator

  frontend-load-balancer:
    image: nginx:latest
    volumes:
      - ./frontend_nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    ports:
      - "5000:80"
