version: "3"
services:

  coordinator:
    build:
      context: .
      dockerfile: coordinator/coordinator.dockerfile
    image: dev/universalis-coordinator:latest
    ports:
      - "8886:8888"
    environment:
      - KAFKA_URL=kafka1:9092

  worker:
    build:
      context: .
      dockerfile: worker/worker.dockerfile
    image: dev/universalis:latest
    env_file:
      - worker/.env
    volumes:
      - ./client/results:/usr/local/universalis/results